### ISSUE TITLE
Provide sensible default for where CA certificates are expected to be found

### ISSUE THREAD

**Issue by mikonieminen** [oxidizing/letters#10]
Currently user of this library needs to provide path where to find CA certificates for making secure connections. Instead of always requiring user to pass this path explicitly, we should provide sensible default value or find out it during build time.

**Comment by mikonieminen** [comment]
This blog post seems to provide good information: https://www.happyassassin.net/posts/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/

**Comment by mikonieminen** [comment]
If system has cURL installed, finding the default location for CA certificates can be read with `curl-config --ca`

**Comment by aronerben** [comment]
https://github.com/curl/curl/blob/master/curl-config.in

**Comment by hannesm** [comment]
at https://github.com/mirage/ca-certs a solution of this issue was worked on, which could be completed.

**Comment by mikonieminen** [comment]
Nice, this looks pretty much what I was thinking we need to do. I did read that in cURL using single CA bundle is slower that reading multiple CA files from CA path (for example all pem files in */etc/ssl/certs*. Though, I don't still understand why exactly. Could be that you can run verifications in parallel.

**Comment by mikonieminen** [comment]
Done.
